package com.cmrt.pfe.models.enums;

public enum NotificationType {
    STAGE_STARTED,
    STAGE_COMPLETED,
    APPROVAL_REQUESTED,
    APPROVAL_GRANTED,
    APPROVAL_REJECTED,
    ISSUE_CREATED,
    ISSUE_ASSIGNED,
    ISSUE_RESOLVED,
    TASK_ASSIGNED,
    TASK_DUE_SOON,
    TASK_OVERDUE,
    RESERVATION_REQUESTED,
    RESERVATION_APPROVED,
    RESERVATION_REJECTED,
    DOCUMENT_UPLOADED,
    DOCUMENT_APPROVED,
    ECR_SUBMITTED,
    ECR_APPROVED,
    DEADLINE_ALERT,
    PRODUCT_ASSIGNED,
    GENERIC
}
